// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAPI.Infrastructure.DbContext;

#nullable disable

namespace UserAPI.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserAPI.Core.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPets")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1a7c621-4c36-4c0b-8a3d-b0fbc9dfe8a6"),
                            Email = "john.doe@example.com",
                            PasswordHash = "hashed_password123",
                            UserPets = "[\"5acb1435-8cc9-42e4-a365-dfa8f9c88d26\"]",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = new Guid("b2a8c621-5e12-4c0b-8d3f-b1fbc9dfe9b7"),
                            Email = "jane.smith@example.com",
                            PasswordHash = "hashed_password456",
                            UserPets = "[\"32e7a77e-0146-4b15-b7f8-58c447641910\",\"ab16dbca-ef93-4c7b-855d-774f89cfab69\"]",
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = new Guid("c3b9d721-6f23-4d2c-8e4f-c2fbc9dfea89"),
                            Email = "alice.johnson@example.com",
                            PasswordHash = "hashed_password789",
                            UserPets = "[]",
                            Username = "alice_johnson"
                        },
                        new
                        {
                            Id = new Guid("d4c8e831-7a34-4e3d-8f5e-d3fbc9dfeab0"),
                            Email = "bob.brown@example.com",
                            PasswordHash = "hashed_password012",
                            UserPets = "[\"0d8e8e7e-0145-4b20-bb9f-58c447641912\"]",
                            Username = "bob_brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
